---

docker_version: '1.12.1'
docker_install_docker_compose: True
docker_compose_version: '1.8.1'

docker_users: []

docker_options: []

docker_apt_key: '58118E89F3A912897C070ADBF76221572C52609D'

docker_distribution: '{{ ansible_local.core.distribution
                         if (ansible_local|d() and ansible_local.core|d() and
                             ansible_local.core.distribution|d())
                         else ansible_distribution }}'
docker_distribution_release: '{{ ansible_local.core.distribution_release
                                 if (ansible_local|d() and ansible_local.core|d() and
                                     ansible_local.core.distribution_release|d())
                                 else ansible_distribution_release }}'

docker_repository: 'deb https://apt.dockerproject.org/repo {{ docker_distribution | lower }}-{{ docker_distribution_release }} main'

docker_apt_cache_time: 86400
