- hosts: web
  remote_user: root
  vars:
    firewall_allowed_tcp_ports:
      - "80"
      - "22"
  roles:
    - { role: dimtheo.firewall }
      
- hosts: test
  remote_user: root
  vars:
    firewall_allowed_tcp_ports:
      - "22"     
  roles:
    - { role: dimtheo.firewall }

- hosts: https
  remote_user: root
  vars:
    firewall_allowed_tcp_ports:
      - "5000"
    firewall_deny_tcp_ports:
      - "22"
  roles:
     - { role: dimtheo.firewall }
  tasks:
    - debug: var=firewall_allowed_tcp_ports
