- hosts: zones
  remote_user: root
  tasks:
  - name: enable backports
    apt_repository:
      repo='deb http://http.debian.net/debian jessie-backports main'
  - name: install python-pip
    package:
      name: python-pip
        
  
  - name:  docker
    apt:
      name=docker.io
  - name: install docker-py
    easy_install:
      name=docker-py
      #name=python-docker