---
# tasks/client.yml: Deploy various client-side configs for Sensu

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Deploy Sensu client service configuration
    template:
      dest: "{{ sensu_config_path }}/conf.d/client.json"
      owner: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"
      src: "{{ sensu_client_config  }}"
    notify: restart sensu-client service



  - name: Ensure Sensu client service is running
    service: name=sensu-client state=started enabled=yes
   
