apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: emqtt
  name: emqtt
spec:
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "8083"
    port: 8083
    targetPort: 8083
  - name: "18083"
    port: 18083
    targetPort: 18083
  selector:
    io.kompose.service: emqtt
status:
  loadBalancer: {}
